name: Build and Deploy QEMU x86_64 Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Tag
        id: set_tag
        run: echo "::set-output name=IMAGE_TAG::$(echo $GITHUB_SHA | cut -c1-12)"

      - name: Build Docker Image
        run: |
          # Build the Docker image with a generic tag
          docker build -t rkbvn89/qemu_x86_64_yocto:${{ steps.set_tag.outputs.IMAGE_TAG }} .

      - name: Push Docker Image
        run: |
          # Push the Docker image to a container registry (e.g., Docker Hub)
          echo ${{ secrets.DOCKER_PAT }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push rkbvn89/qemu_x86_64_yocto:${{ steps.set_tag.outputs.IMAGE_TAG }}