name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build --rm --tag rkbvn89/qemu_x86_64_yocto:${{ github.sha }} -f Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - name: Login to Docker Hub
      run: | 
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Push Docker image to Docker Hub
      run: docker push rkbvn89/qemu_x86_64_yocto:${{ github.sha }}
